# resolver: lts-3.15
# resolver: lts-7.7
resolver: lts-13.16

# Local packages, usually specified by relative directory name
packages:
- '.'
- ./msgs/Std_msgs
- ./msgs/Std_srvs
- ./msgs/Geometry_msgs
- ./msgs/Sensor_msgs
- ./msgs/Actionlib_msgs
- ./msgs/Nav_msgs
- ./msgs/Turtlesim
- ./Examples/PubSub

# Packages to be pulled from upstream that are not in the resolver (e.g., acme-missiles-0.3)
extra-deps:
- data-default-generics-0.3
- storable-tuple-0.0.3.3
- storable-record-0.0.4
# - utility-ht-0.0.12
- uri-0.1.6.4
- haxr-3000.11.3
- HaXml-1.25.5

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

nix:
  packages: [openssl, zlib]

# docker:
#   image: roshask
